/**
 * Swing-review screenshots, as the cloud keeps them.
 *
 * A screenshot used to travel as words only: the analysis file carried its
 * title, note and timestamp, and the picture was stripped before upload
 * because a handful of PNG data URLs would blow the function's request limit.
 * The picture now travels on its own, as one small JPEG per screenshot in the
 * same Drive folder as the video, and the analysis file records its id.
 *
 * This module owns the judgement: which uploads are accepted, how a picture is
 * labelled in Drive so it can be found again, and what of a screenshot a
 * reader is handed. The routes in video-transfer.mts own the bytes.
 */

const text = (value: unknown, max = 600) => String(value ?? "").trim().slice(0, max);

/** Big enough for a full 4K frame as a JPEG, small enough that one request
 *  stays well inside Netlify's ~6 MB body limit. The client downsizes first. */
export const MAX_SNAPSHOT_IMAGE_BYTES = 3 * 1024 * 1024;

export const SNAPSHOT_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"] as const;

/** Snapshot ids are generated by the coach app (`focus-left-…`, `frame-right-…`).
 *  They end up in a Drive query and a URL, so only a plain id is accepted. */
export function safeSnapshotId(value: unknown): string {
  const id = text(value, 120);
  return /^[A-Za-z0-9._-]+$/.test(id) ? id : "";
}

export type SnapshotUploadVerdict =
  | { ok: true; mimeType: (typeof SNAPSHOT_IMAGE_TYPES)[number] }
  | { ok: false; status: number; reason: string };

export function snapshotUploadVerdict(input: {
  snapshotId: string;
  contentType: string | null;
  sizeBytes: number;
}): SnapshotUploadVerdict {
  if (!input.snapshotId) {
    return { ok: false, status: 400, reason: "Screenshot id is missing or invalid." };
  }
  const mimeType = text(input.contentType, 80).split(";")[0].trim().toLowerCase();
  const allowed = SNAPSHOT_IMAGE_TYPES.find((type) => type === mimeType);
  if (!allowed) {
    return { ok: false, status: 415, reason: "Screenshots must be sent as JPEG, PNG or WebP." };
  }
  if (!Number.isFinite(input.sizeBytes) || input.sizeBytes <= 0) {
    return { ok: false, status: 400, reason: "The screenshot was empty." };
  }
  if (input.sizeBytes > MAX_SNAPSHOT_IMAGE_BYTES) {
    return { ok: false, status: 413, reason: "That screenshot is too large to upload." };
  }
  return { ok: true, mimeType: allowed };
}

/** How a screenshot's picture is labelled in Drive. The saved video and account
 *  are part of the key so a lookup can never land on another video's picture,
 *  even inside a folder that was moved by hand. */
export function snapshotImageAppProperties(input: {
  accountId: string;
  savedVideoId: string;
  snapshotId: string;
  clarityVersion: string;
}): Record<string, string> {
  return {
    clarityType: "focus-snapshot",
    clarityAccountId: input.accountId,
    claritySavedVideoId: input.savedVideoId,
    claritySnapshotId: input.snapshotId,
    clarityVersion: input.clarityVersion,
  };
}

export function snapshotImageFileName(snapshotId: string, mimeType: string): string {
  const extension = mimeType === "image/png" ? "png" : mimeType === "image/webp" ? "webp" : "jpg";
  return `snapshot-${snapshotId}.${extension}`;
}

export type SnapshotRect = { x: number; y: number; width: number; height: number };

/**
 * One screenshot, as any reader of the cloud copy sees it: the portal, a coach
 * on another device, and the emailed review page.
 *
 * `cropRect` is the part of the frame it was taken from, normalised 0–1 to the
 * video, which is what lets a reader wind the video to `currentTime` and draw
 * a box where the coach drew theirs. No Drive ids leave here -- `hasImage` is
 * all a reader needs to know whether to ask for the picture.
 */
export type PublicSnapshot = {
  id: string;
  title: string;
  note: string;
  currentTime: number;
  captureKind: "frame" | "area";
  cropRect: SnapshotRect | null;
  hasImage: boolean;
};

const unit = (value: unknown) => {
  const number = Number(value);
  if (!Number.isFinite(number)) return null;
  return Math.min(1, Math.max(0, number));
};

export function snapshotRect(value: unknown): SnapshotRect | null {
  if (!value || typeof value !== "object") return null;
  const rect = value as Record<string, unknown>;
  const x = unit(rect.x);
  const y = unit(rect.y);
  const width = unit(rect.width);
  const height = unit(rect.height);
  if (x === null || y === null || width === null || height === null) return null;
  if (width <= 0 || height <= 0) return null;
  return { x, y, width: Math.min(width, 1 - x), height: Math.min(height, 1 - y) };
}

const seconds = (value: unknown) => {
  const number = Number(value);
  return Number.isFinite(number) && number >= 0 ? number : 0;
};

export function publicSnapshots(analysis: unknown): PublicSnapshot[] {
  const list = (analysis as any)?.analysis?.focusSnapshots;
  if (!Array.isArray(list)) return [];
  return list
    .map((snapshot: any, index: number): PublicSnapshot => {
      const captureKind = snapshot?.captureKind === "frame" ? "frame" : "area";
      return {
        id: safeSnapshotId(snapshot?.id) || `snapshot-${index}`,
        title: text(snapshot?.title, 180) || "Screenshot",
        note: text(snapshot?.note, 2000),
        currentTime: seconds(snapshot?.currentTime),
        captureKind,
        cropRect: captureKind === "frame" ? null : snapshotRect(snapshot?.cropRect),
        hasImage: Boolean(text(snapshot?.imageFileId, 180)),
      };
    })
    .sort((left, right) => left.currentTime - right.currentTime);
}

/** Does the analysis file name this screenshot as having a picture? The image
 *  routes check this before touching Drive, so an id that was never part of
 *  the video is a 404 without a Drive round trip. */
export function snapshotHasImage(analysis: unknown, snapshotId: string): boolean {
  return publicSnapshots(analysis).some((snapshot) => snapshot.id === snapshotId && snapshot.hasImage);
}

/**
 * The incoming analysis, with any picture link the previous one had and the
 * incoming one lacks carried over by screenshot id. Only fills gaps: a
 * screenshot the sender deleted stays deleted, and one it re-uploaded keeps
 * the id it sent.
 */
export function carryImageFileIds<T extends Record<string, unknown>>(previous: unknown, incoming: T): T {
  const before = (previous as any)?.analysis?.focusSnapshots;
  const after = (incoming as any)?.analysis?.focusSnapshots;
  if (!Array.isArray(before) || !Array.isArray(after)) return incoming;
  const known = new Map<string, string>();
  for (const snapshot of before) {
    const id = safeSnapshotId(snapshot?.id);
    const fileId = text(snapshot?.imageFileId, 180);
    if (id && fileId) known.set(id, fileId);
  }
  if (!known.size) return incoming;
  return {
    ...incoming,
    analysis: {
      ...(incoming as any).analysis,
      focusSnapshots: after.map((snapshot: any) => {
        const id = safeSnapshotId(snapshot?.id);
        if (!id || text(snapshot?.imageFileId, 180) || !known.has(id)) return snapshot;
        return { ...snapshot, imageFileId: known.get(id) };
      }),
    },
  };
}
