// Generated from the IANA tz database's zone.tab (tzdata 2025b): every
// country's time zones, in the database's own order, with its note for telling
// them apart. Regenerate from a newer tzdata rather than editing by hand.

export const TIME_ZONES_BY_COUNTRY: Record<string, ReadonlyArray<readonly [zone: string, note: string]>> = {
  AD: [["Europe/Andorra", ""]],
  AE: [["Asia/Dubai", ""]],
  AF: [["Asia/Kabul", ""]],
  AG: [["America/Antigua", ""]],
  AI: [["America/Anguilla", ""]],
  AL: [["Europe/Tirane", ""]],
  AM: [["Asia/Yerevan", ""]],
  AO: [["Africa/Luanda", ""]],
  AQ: [["Antarctica/McMurdo", "New Zealand time - McMurdo, South Pole"], ["Antarctica/Casey", "Casey"], ["Antarctica/Davis", "Davis"], ["Antarctica/DumontDUrville", "Dumont-d'Urville"], ["Antarctica/Mawson", "Mawson"], ["Antarctica/Palmer", "Palmer"], ["Antarctica/Rothera", "Rothera"], ["Antarctica/Syowa", "Syowa"], ["Antarctica/Troll", "Troll"], ["Antarctica/Vostok", "Vostok"]],
  AR: [["America/Argentina/Buenos_Aires", "Buenos Aires (BA, CF)"], ["America/Argentina/Cordoba", "Argentina (most areas: CB, CC, CN, ER, FM, MN, SE, SF)"], ["America/Argentina/Salta", "Salta (SA, LP, NQ, RN)"], ["America/Argentina/Jujuy", "Jujuy (JY)"], ["America/Argentina/Tucuman", "Tucuman (TM)"], ["America/Argentina/Catamarca", "Catamarca (CT), Chubut (CH)"], ["America/Argentina/La_Rioja", "La Rioja (LR)"], ["America/Argentina/San_Juan", "San Juan (SJ)"], ["America/Argentina/Mendoza", "Mendoza (MZ)"], ["America/Argentina/San_Luis", "San Luis (SL)"], ["America/Argentina/Rio_Gallegos", "Santa Cruz (SC)"], ["America/Argentina/Ushuaia", "Tierra del Fuego (TF)"]],
  AS: [["Pacific/Pago_Pago", ""]],
  AT: [["Europe/Vienna", ""]],
  AU: [["Australia/Lord_Howe", "Lord Howe Island"], ["Antarctica/Macquarie", "Macquarie Island"], ["Australia/Hobart", "Tasmania"], ["Australia/Melbourne", "Victoria"], ["Australia/Sydney", "New South Wales (most areas)"], ["Australia/Broken_Hill", "New South Wales (Yancowinna)"], ["Australia/Brisbane", "Queensland (most areas)"], ["Australia/Lindeman", "Queensland (Whitsunday Islands)"], ["Australia/Adelaide", "South Australia"], ["Australia/Darwin", "Northern Territory"], ["Australia/Perth", "Western Australia (most areas)"], ["Australia/Eucla", "Western Australia (Eucla)"]],
  AW: [["America/Aruba", ""]],
  AX: [["Europe/Mariehamn", ""]],
  AZ: [["Asia/Baku", ""]],
  BA: [["Europe/Sarajevo", ""]],
  BB: [["America/Barbados", ""]],
  BD: [["Asia/Dhaka", ""]],
  BE: [["Europe/Brussels", ""]],
  BF: [["Africa/Ouagadougou", ""]],
  BG: [["Europe/Sofia", ""]],
  BH: [["Asia/Bahrain", ""]],
  BI: [["Africa/Bujumbura", ""]],
  BJ: [["Africa/Porto-Novo", ""]],
  BL: [["America/St_Barthelemy", ""]],
  BM: [["Atlantic/Bermuda", ""]],
  BN: [["Asia/Brunei", ""]],
  BO: [["America/La_Paz", ""]],
  BQ: [["America/Kralendijk", ""]],
  BR: [["America/Noronha", "Atlantic islands"], ["America/Belem", "Para (east), Amapa"], ["America/Fortaleza", "Brazil (northeast: MA, PI, CE, RN, PB)"], ["America/Recife", "Pernambuco"], ["America/Araguaina", "Tocantins"], ["America/Maceio", "Alagoas, Sergipe"], ["America/Bahia", "Bahia"], ["America/Sao_Paulo", "Brazil (southeast: GO, DF, MG, ES, RJ, SP, PR, SC, RS)"], ["America/Campo_Grande", "Mato Grosso do Sul"], ["America/Cuiaba", "Mato Grosso"], ["America/Santarem", "Para (west)"], ["America/Porto_Velho", "Rondonia"], ["America/Boa_Vista", "Roraima"], ["America/Manaus", "Amazonas (east)"], ["America/Eirunepe", "Amazonas (west)"], ["America/Rio_Branco", "Acre"]],
  BS: [["America/Nassau", ""]],
  BT: [["Asia/Thimphu", ""]],
  BW: [["Africa/Gaborone", ""]],
  BY: [["Europe/Minsk", ""]],
  BZ: [["America/Belize", ""]],
  CA: [["America/St_Johns", "Newfoundland, Labrador (SE)"], ["America/Halifax", "Atlantic - NS (most areas), PE"], ["America/Glace_Bay", "Atlantic - NS (Cape Breton)"], ["America/Moncton", "Atlantic - New Brunswick"], ["America/Goose_Bay", "Atlantic - Labrador (most areas)"], ["America/Blanc-Sablon", "AST - QC (Lower North Shore)"], ["America/Toronto", "Eastern - ON & QC (most areas)"], ["America/Iqaluit", "Eastern - NU (most areas)"], ["America/Atikokan", "EST - ON (Atikokan), NU (Coral H)"], ["America/Winnipeg", "Central - ON (west), Manitoba"], ["America/Resolute", "Central - NU (Resolute)"], ["America/Rankin_Inlet", "Central - NU (central)"], ["America/Regina", "CST - SK (most areas)"], ["America/Swift_Current", "CST - SK (midwest)"], ["America/Edmonton", "Mountain - AB, BC(E), NT(E), SK(W)"], ["America/Cambridge_Bay", "Mountain - NU (west)"], ["America/Inuvik", "Mountain - NT (west)"], ["America/Creston", "MST - BC (Creston)"], ["America/Dawson_Creek", "MST - BC (Dawson Cr, Ft St John)"], ["America/Fort_Nelson", "MST - BC (Ft Nelson)"], ["America/Whitehorse", "MST - Yukon (east)"], ["America/Dawson", "MST - Yukon (west)"], ["America/Vancouver", "Pacific - BC (most areas)"]],
  CC: [["Indian/Cocos", ""]],
  CD: [["Africa/Kinshasa", "Dem. Rep. of Congo (west)"], ["Africa/Lubumbashi", "Dem. Rep. of Congo (east)"]],
  CF: [["Africa/Bangui", ""]],
  CG: [["Africa/Brazzaville", ""]],
  CH: [["Europe/Zurich", ""]],
  CI: [["Africa/Abidjan", ""]],
  CK: [["Pacific/Rarotonga", ""]],
  CL: [["America/Santiago", "most of Chile"], ["America/Coyhaique", "Aysen Region"], ["America/Punta_Arenas", "Magallanes Region"], ["Pacific/Easter", "Easter Island"]],
  CM: [["Africa/Douala", ""]],
  CN: [["Asia/Shanghai", "Beijing Time"], ["Asia/Urumqi", "Xinjiang Time"]],
  CO: [["America/Bogota", ""]],
  CR: [["America/Costa_Rica", ""]],
  CU: [["America/Havana", ""]],
  CV: [["Atlantic/Cape_Verde", ""]],
  CW: [["America/Curacao", ""]],
  CX: [["Indian/Christmas", ""]],
  CY: [["Asia/Nicosia", "most of Cyprus"], ["Asia/Famagusta", "Northern Cyprus"]],
  CZ: [["Europe/Prague", ""]],
  DE: [["Europe/Berlin", "most of Germany"], ["Europe/Busingen", "Busingen"]],
  DJ: [["Africa/Djibouti", ""]],
  DK: [["Europe/Copenhagen", ""]],
  DM: [["America/Dominica", ""]],
  DO: [["America/Santo_Domingo", ""]],
  DZ: [["Africa/Algiers", ""]],
  EC: [["America/Guayaquil", "Ecuador (mainland)"], ["Pacific/Galapagos", "Galapagos Islands"]],
  EE: [["Europe/Tallinn", ""]],
  EG: [["Africa/Cairo", ""]],
  EH: [["Africa/El_Aaiun", ""]],
  ER: [["Africa/Asmara", ""]],
  ES: [["Europe/Madrid", "Spain (mainland)"], ["Africa/Ceuta", "Ceuta, Melilla"], ["Atlantic/Canary", "Canary Islands"]],
  ET: [["Africa/Addis_Ababa", ""]],
  FI: [["Europe/Helsinki", ""]],
  FJ: [["Pacific/Fiji", ""]],
  FK: [["Atlantic/Stanley", ""]],
  FM: [["Pacific/Chuuk", "Chuuk/Truk, Yap"], ["Pacific/Pohnpei", "Pohnpei/Ponape"], ["Pacific/Kosrae", "Kosrae"]],
  FO: [["Atlantic/Faroe", ""]],
  FR: [["Europe/Paris", ""]],
  GA: [["Africa/Libreville", ""]],
  GB: [["Europe/London", ""]],
  GD: [["America/Grenada", ""]],
  GE: [["Asia/Tbilisi", ""]],
  GF: [["America/Cayenne", ""]],
  GG: [["Europe/Guernsey", ""]],
  GH: [["Africa/Accra", ""]],
  GI: [["Europe/Gibraltar", ""]],
  GL: [["America/Nuuk", "most of Greenland"], ["America/Danmarkshavn", "National Park (east coast)"], ["America/Scoresbysund", "Scoresbysund/Ittoqqortoormiit"], ["America/Thule", "Thule/Pituffik"]],
  GM: [["Africa/Banjul", ""]],
  GN: [["Africa/Conakry", ""]],
  GP: [["America/Guadeloupe", ""]],
  GQ: [["Africa/Malabo", ""]],
  GR: [["Europe/Athens", ""]],
  GS: [["Atlantic/South_Georgia", ""]],
  GT: [["America/Guatemala", ""]],
  GU: [["Pacific/Guam", ""]],
  GW: [["Africa/Bissau", ""]],
  GY: [["America/Guyana", ""]],
  HK: [["Asia/Hong_Kong", ""]],
  HN: [["America/Tegucigalpa", ""]],
  HR: [["Europe/Zagreb", ""]],
  HT: [["America/Port-au-Prince", ""]],
  HU: [["Europe/Budapest", ""]],
  ID: [["Asia/Jakarta", "Java, Sumatra"], ["Asia/Pontianak", "Borneo (west, central)"], ["Asia/Makassar", "Borneo (east, south), Sulawesi/Celebes, Bali, Nusa Tengarra, Timor (west)"], ["Asia/Jayapura", "New Guinea (West Papua / Irian Jaya), Malukus/Moluccas"]],
  IE: [["Europe/Dublin", ""]],
  IL: [["Asia/Jerusalem", ""]],
  IM: [["Europe/Isle_of_Man", ""]],
  IN: [["Asia/Kolkata", ""]],
  IO: [["Indian/Chagos", ""]],
  IQ: [["Asia/Baghdad", ""]],
  IR: [["Asia/Tehran", ""]],
  IS: [["Atlantic/Reykjavik", ""]],
  IT: [["Europe/Rome", ""]],
  JE: [["Europe/Jersey", ""]],
  JM: [["America/Jamaica", ""]],
  JO: [["Asia/Amman", ""]],
  JP: [["Asia/Tokyo", ""]],
  KE: [["Africa/Nairobi", ""]],
  KG: [["Asia/Bishkek", ""]],
  KH: [["Asia/Phnom_Penh", ""]],
  KI: [["Pacific/Tarawa", "Gilbert Islands"], ["Pacific/Kanton", "Phoenix Islands"], ["Pacific/Kiritimati", "Line Islands"]],
  KM: [["Indian/Comoro", ""]],
  KN: [["America/St_Kitts", ""]],
  KP: [["Asia/Pyongyang", ""]],
  KR: [["Asia/Seoul", ""]],
  KW: [["Asia/Kuwait", ""]],
  KY: [["America/Cayman", ""]],
  KZ: [["Asia/Almaty", "most of Kazakhstan"], ["Asia/Qyzylorda", "Qyzylorda/Kyzylorda/Kzyl-Orda"], ["Asia/Qostanay", "Qostanay/Kostanay/Kustanay"], ["Asia/Aqtobe", "Aqtobe/Aktobe"], ["Asia/Aqtau", "Mangghystau/Mankistau"], ["Asia/Atyrau", "Atyrau/Atirau/Gur'yev"], ["Asia/Oral", "West Kazakhstan"]],
  LA: [["Asia/Vientiane", ""]],
  LB: [["Asia/Beirut", ""]],
  LC: [["America/St_Lucia", ""]],
  LI: [["Europe/Vaduz", ""]],
  LK: [["Asia/Colombo", ""]],
  LR: [["Africa/Monrovia", ""]],
  LS: [["Africa/Maseru", ""]],
  LT: [["Europe/Vilnius", ""]],
  LU: [["Europe/Luxembourg", ""]],
  LV: [["Europe/Riga", ""]],
  LY: [["Africa/Tripoli", ""]],
  MA: [["Africa/Casablanca", ""]],
  MC: [["Europe/Monaco", ""]],
  MD: [["Europe/Chisinau", ""]],
  ME: [["Europe/Podgorica", ""]],
  MF: [["America/Marigot", ""]],
  MG: [["Indian/Antananarivo", ""]],
  MH: [["Pacific/Majuro", "most of Marshall Islands"], ["Pacific/Kwajalein", "Kwajalein"]],
  MK: [["Europe/Skopje", ""]],
  ML: [["Africa/Bamako", ""]],
  MM: [["Asia/Yangon", ""]],
  MN: [["Asia/Ulaanbaatar", "most of Mongolia"], ["Asia/Hovd", "Bayan-Olgii, Hovd, Uvs"]],
  MO: [["Asia/Macau", ""]],
  MP: [["Pacific/Saipan", ""]],
  MQ: [["America/Martinique", ""]],
  MR: [["Africa/Nouakchott", ""]],
  MS: [["America/Montserrat", ""]],
  MT: [["Europe/Malta", ""]],
  MU: [["Indian/Mauritius", ""]],
  MV: [["Indian/Maldives", ""]],
  MW: [["Africa/Blantyre", ""]],
  MX: [["America/Mexico_City", "Central Mexico"], ["America/Cancun", "Quintana Roo"], ["America/Merida", "Campeche, Yucatan"], ["America/Monterrey", "Durango; Coahuila, Nuevo Leon, Tamaulipas (most areas)"], ["America/Matamoros", "Coahuila, Nuevo Leon, Tamaulipas (US border)"], ["America/Chihuahua", "Chihuahua (most areas)"], ["America/Ciudad_Juarez", "Chihuahua (US border - west)"], ["America/Ojinaga", "Chihuahua (US border - east)"], ["America/Mazatlan", "Baja California Sur, Nayarit (most areas), Sinaloa"], ["America/Bahia_Banderas", "Bahia de Banderas"], ["America/Hermosillo", "Sonora"], ["America/Tijuana", "Baja California"]],
  MY: [["Asia/Kuala_Lumpur", "Malaysia (peninsula)"], ["Asia/Kuching", "Sabah, Sarawak"]],
  MZ: [["Africa/Maputo", ""]],
  NA: [["Africa/Windhoek", ""]],
  NC: [["Pacific/Noumea", ""]],
  NE: [["Africa/Niamey", ""]],
  NF: [["Pacific/Norfolk", ""]],
  NG: [["Africa/Lagos", ""]],
  NI: [["America/Managua", ""]],
  NL: [["Europe/Amsterdam", ""]],
  NO: [["Europe/Oslo", ""]],
  NP: [["Asia/Kathmandu", ""]],
  NR: [["Pacific/Nauru", ""]],
  NU: [["Pacific/Niue", ""]],
  NZ: [["Pacific/Auckland", "most of New Zealand"], ["Pacific/Chatham", "Chatham Islands"]],
  OM: [["Asia/Muscat", ""]],
  PA: [["America/Panama", ""]],
  PE: [["America/Lima", ""]],
  PF: [["Pacific/Tahiti", "Society Islands"], ["Pacific/Marquesas", "Marquesas Islands"], ["Pacific/Gambier", "Gambier Islands"]],
  PG: [["Pacific/Port_Moresby", "most of Papua New Guinea"], ["Pacific/Bougainville", "Bougainville"]],
  PH: [["Asia/Manila", ""]],
  PK: [["Asia/Karachi", ""]],
  PL: [["Europe/Warsaw", ""]],
  PM: [["America/Miquelon", ""]],
  PN: [["Pacific/Pitcairn", ""]],
  PR: [["America/Puerto_Rico", ""]],
  PS: [["Asia/Gaza", "Gaza Strip"], ["Asia/Hebron", "West Bank"]],
  PT: [["Europe/Lisbon", "Portugal (mainland)"], ["Atlantic/Madeira", "Madeira Islands"], ["Atlantic/Azores", "Azores"]],
  PW: [["Pacific/Palau", ""]],
  PY: [["America/Asuncion", ""]],
  QA: [["Asia/Qatar", ""]],
  RE: [["Indian/Reunion", ""]],
  RO: [["Europe/Bucharest", ""]],
  RS: [["Europe/Belgrade", ""]],
  RU: [["Europe/Kaliningrad", "MSK-01 - Kaliningrad"], ["Europe/Moscow", "MSK+00 - Moscow area"], ["Europe/Kirov", "MSK+00 - Kirov"], ["Europe/Volgograd", "MSK+00 - Volgograd"], ["Europe/Astrakhan", "MSK+01 - Astrakhan"], ["Europe/Saratov", "MSK+01 - Saratov"], ["Europe/Ulyanovsk", "MSK+01 - Ulyanovsk"], ["Europe/Samara", "MSK+01 - Samara, Udmurtia"], ["Asia/Yekaterinburg", "MSK+02 - Urals"], ["Asia/Omsk", "MSK+03 - Omsk"], ["Asia/Novosibirsk", "MSK+04 - Novosibirsk"], ["Asia/Barnaul", "MSK+04 - Altai"], ["Asia/Tomsk", "MSK+04 - Tomsk"], ["Asia/Novokuznetsk", "MSK+04 - Kemerovo"], ["Asia/Krasnoyarsk", "MSK+04 - Krasnoyarsk area"], ["Asia/Irkutsk", "MSK+05 - Irkutsk, Buryatia"], ["Asia/Chita", "MSK+06 - Zabaykalsky"], ["Asia/Yakutsk", "MSK+06 - Lena River"], ["Asia/Khandyga", "MSK+06 - Tomponsky, Ust-Maysky"], ["Asia/Vladivostok", "MSK+07 - Amur River"], ["Asia/Ust-Nera", "MSK+07 - Oymyakonsky"], ["Asia/Magadan", "MSK+08 - Magadan"], ["Asia/Sakhalin", "MSK+08 - Sakhalin Island"], ["Asia/Srednekolymsk", "MSK+08 - Sakha (E), N Kuril Is"], ["Asia/Kamchatka", "MSK+09 - Kamchatka"], ["Asia/Anadyr", "MSK+09 - Bering Sea"]],
  RW: [["Africa/Kigali", ""]],
  SA: [["Asia/Riyadh", ""]],
  SB: [["Pacific/Guadalcanal", ""]],
  SC: [["Indian/Mahe", ""]],
  SD: [["Africa/Khartoum", ""]],
  SE: [["Europe/Stockholm", ""]],
  SG: [["Asia/Singapore", ""]],
  SH: [["Atlantic/St_Helena", ""]],
  SI: [["Europe/Ljubljana", ""]],
  SJ: [["Arctic/Longyearbyen", ""]],
  SK: [["Europe/Bratislava", ""]],
  SL: [["Africa/Freetown", ""]],
  SM: [["Europe/San_Marino", ""]],
  SN: [["Africa/Dakar", ""]],
  SO: [["Africa/Mogadishu", ""]],
  SR: [["America/Paramaribo", ""]],
  SS: [["Africa/Juba", ""]],
  ST: [["Africa/Sao_Tome", ""]],
  SV: [["America/El_Salvador", ""]],
  SX: [["America/Lower_Princes", ""]],
  SY: [["Asia/Damascus", ""]],
  SZ: [["Africa/Mbabane", ""]],
  TC: [["America/Grand_Turk", ""]],
  TD: [["Africa/Ndjamena", ""]],
  TF: [["Indian/Kerguelen", ""]],
  TG: [["Africa/Lome", ""]],
  TH: [["Asia/Bangkok", ""]],
  TJ: [["Asia/Dushanbe", ""]],
  TK: [["Pacific/Fakaofo", ""]],
  TL: [["Asia/Dili", ""]],
  TM: [["Asia/Ashgabat", ""]],
  TN: [["Africa/Tunis", ""]],
  TO: [["Pacific/Tongatapu", ""]],
  TR: [["Europe/Istanbul", ""]],
  TT: [["America/Port_of_Spain", ""]],
  TV: [["Pacific/Funafuti", ""]],
  TW: [["Asia/Taipei", ""]],
  TZ: [["Africa/Dar_es_Salaam", ""]],
  UA: [["Europe/Simferopol", "Crimea"], ["Europe/Kyiv", "most of Ukraine"]],
  UG: [["Africa/Kampala", ""]],
  UM: [["Pacific/Midway", "Midway Islands"], ["Pacific/Wake", "Wake Island"]],
  US: [["America/New_York", "Eastern (most areas)"], ["America/Detroit", "Eastern - MI (most areas)"], ["America/Kentucky/Louisville", "Eastern - KY (Louisville area)"], ["America/Kentucky/Monticello", "Eastern - KY (Wayne)"], ["America/Indiana/Indianapolis", "Eastern - IN (most areas)"], ["America/Indiana/Vincennes", "Eastern - IN (Da, Du, K, Mn)"], ["America/Indiana/Winamac", "Eastern - IN (Pulaski)"], ["America/Indiana/Marengo", "Eastern - IN (Crawford)"], ["America/Indiana/Petersburg", "Eastern - IN (Pike)"], ["America/Indiana/Vevay", "Eastern - IN (Switzerland)"], ["America/Chicago", "Central (most areas)"], ["America/Indiana/Tell_City", "Central - IN (Perry)"], ["America/Indiana/Knox", "Central - IN (Starke)"], ["America/Menominee", "Central - MI (Wisconsin border)"], ["America/North_Dakota/Center", "Central - ND (Oliver)"], ["America/North_Dakota/New_Salem", "Central - ND (Morton rural)"], ["America/North_Dakota/Beulah", "Central - ND (Mercer)"], ["America/Denver", "Mountain (most areas)"], ["America/Boise", "Mountain - ID (south), OR (east)"], ["America/Phoenix", "MST - AZ (except Navajo)"], ["America/Los_Angeles", "Pacific"], ["America/Anchorage", "Alaska (most areas)"], ["America/Juneau", "Alaska - Juneau area"], ["America/Sitka", "Alaska - Sitka area"], ["America/Metlakatla", "Alaska - Annette Island"], ["America/Yakutat", "Alaska - Yakutat"], ["America/Nome", "Alaska (west)"], ["America/Adak", "Alaska - western Aleutians"], ["Pacific/Honolulu", "Hawaii"]],
  UY: [["America/Montevideo", ""]],
  UZ: [["Asia/Samarkand", "Uzbekistan (west)"], ["Asia/Tashkent", "Uzbekistan (east)"]],
  VA: [["Europe/Vatican", ""]],
  VC: [["America/St_Vincent", ""]],
  VE: [["America/Caracas", ""]],
  VG: [["America/Tortola", ""]],
  VI: [["America/St_Thomas", ""]],
  VN: [["Asia/Ho_Chi_Minh", ""]],
  VU: [["Pacific/Efate", ""]],
  WF: [["Pacific/Wallis", ""]],
  WS: [["Pacific/Apia", ""]],
  YE: [["Asia/Aden", ""]],
  YT: [["Indian/Mayotte", ""]],
  ZA: [["Africa/Johannesburg", ""]],
  ZM: [["Africa/Lusaka", ""]],
  ZW: [["Africa/Harare", ""]],
};
